# Generated by Django 5.2.1 on 2025-05-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotemplate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='template_previews/'),
        ),
    ]
