# Generated by Django 5.2.1 on 2025-05-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_portfoliotemplate_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
