# Generated by Django 5.2.1 on 2025-05-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_portfolio_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
